default:
  image: python:3.11-slim


stages:
  - linters
  - tests


Tests:
  stage: tests
  services:
    - name: bitnami/postgresql:latest
      alias: cc_postgres
  variables:
    POSTGRES_USER: shift_cc
    POSTGRES_PASSWORD: shift_cc_pass
    POSTGRES_DB: shift_cc_db
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - apt-get -y update && apt-get -y install libgl1
    - apt-get -y update && apt-get -y install libglib2.0-0
  script:
    - poetry run pytest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - "**/*.py"
#      when: manual

Linters:
  stage: linters
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install --without ml
  script:
    - poetry run flake8
    - poetry run mypy .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
