apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.appName | quote }}
  labels:
    app: {{ .Values.config.appName | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.config.appName | quote }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.config.appPort | quote }}
      labels:
        app: {{ .Values.config.appName | quote }}
    spec:
      containers:
        - name: {{ .Values.config.appName | quote }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.config.appPort }}
          livenessProbe:
            httpGet:
              path: /healthz/up
              port: {{ .Values.config.appPort }}
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .Values.config.appPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.appName | quote }}
