apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gran-url.fullname" . }}-postgresql
  labels:
    app: {{ include "gran-url.fullname" . }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gran-url.fullname" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "gran-url.fullname" . }}-postgresql
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:14
        env:
        - name: POSTGRES_USER
          value: {{ .Values.config.postgresDbUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.config.postgresDbPass }}
        - name: POSTGRES_DB
          value: {{ .Values.config.postgresDbName }}
        - name: PGDATA
          value: "/bitnami/postgresql"
        ports:
        - containerPort: {{ .Values.config.postgresPort | int }}
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
      volumes:
      - name: data
        emptyDir: {}
