apiVersion: v1
kind: Service
metadata:
  name: {{ include "gran-url.fullname" . }}-postgresql
  labels:
    app: {{ include "gran-url.fullname" . }}-postgresql
spec:
  ports:
  - port: {{ .Values.config.postgresPort | int }}
  selector:
    app: {{ include "gran-url.fullname" . }}-postgresql
